// <auto-generated />
using System;
using Labb1_OOP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1_OOP.Migrations
{
    [DbContext(typeof(SpelCenterDbContext))]
    [Migration("20260523193503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb1_OOP.Bokning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("maxAntal")
                        .HasColumnType("int");

                    b.Property<DateTime>("slutDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bokning");
                });

            modelBuilder.Entity("Labb1_OOP.Modeller.Medlem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("telefonNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medlem");
                });

            modelBuilder.Entity("Labb1_OOP.Modeller.Spel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("maxAntalSpelare")
                        .HasColumnType("int");

                    b.Property<int>("minAntalSpelare")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Spel");
                });
#pragma warning restore 612, 618
        }
    }
}
